function renderFilters(){const v=[['ALL','Todo CRM',SUMMARY.total],['SENT','Enviados',SUMMARY.sent],['QUEUE','Preparados',SUMMARY.queue],['INTERESTED','Interesados',SUMMARY.interested],['WON','Conseguido',SUMMARY.won],['NEXT','Próximos pasos',SUMMARY.next],['ROADMAP','Roadmap 12M',D?.roadmap?.length||36]];document.getElementById('views').innerHTML=v.map(x=>`<button class="pill ${view===x[0]?'active':''}" data-view="${x[0]}">${x[1]} <span class="count">${x[2]}</span></button>`).join('');
const p=[['ALL','Todos',SUMMARY.creators+SUMMARY.guides+SUMMARY.agencies+SUMMARY.partners,''],['CREADOR','Creadores',SUMMARY.creators,'Obj. '+TARGETS.creators],['GUIA','Guías',SUMMARY.guides,'Obj. '+TARGETS.guides],['AGENCIA','Agencias',SUMMARY.agencies,'Obj. '+TARGETS.agencies],['PARTNER_LOCAL','Partners',SUMMARY.partners,'Obj. '+TARGETS.partners]];document.getElementById('profiles').innerHTML=p.map(x=>`<button class="pill profilePill ${profile===x[0]?'active':''}" data-profile="${x[0]}">${x[1]} <span class="count">${x[2]}</span>${x[3]?`<span class="target">/${x[3].replace('Obj. ','')}</span>`:''}</button>`).join('');
const fs=[['ALL','Todos'],['SUPPLY','Experiencias'],['PARTNER','Partners'],['INSTITUTION','Instituciones'],['CAPITAL','Capital'],['CONTEST','Concursos']];document.getElementById('funnels').innerHTML=fs.map(x=>`<button class="pill ${funnel===x[0]?'active':''}" data-funnel="${x[0]}">${x[1]}</button>`).join('');
const qs=[['ALL','12 meses'],['Q4','Q4 2026'],['Q1','Q1 2027'],['Q2','Q2 2027'],['Q3','Q3 2027']];document.getElementById('quarters').innerHTML=qs.map(x=>`<button class="pill ${quarter===x[0]?'active':''}" data-quarter="${x[0]}">${x[1]}</button>`).join('');
document.getElementById('quarterBox').style.display=view==='ROADMAP'?'block':'none';document.getElementById('funnelBox').style.display=(view==='ALL'&&profile==='ALL')?'block':'none';document.getElementById('profileBox').style.display=view==='ROADMAP'?'none':'block';
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;if(view==='ROADMAP')profile='ALL';selected=null;refresh()});document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{profile=b.dataset.profile;funnel='ALL';selected=null;refresh()});document.querySelectorAll('[data-funnel]').forEach(b=>b.onclick=()=>{funnel=b.dataset.funnel;selected=null;refresh()});document.querySelectorAll('[data-quarter]').forEach(b=>b.onclick=()=>{quarter=b.dataset.quarter;selected=null;refresh(true)})}
function photo(city){return PHOTOS[normCity(city)]||FALLBACK}
function rowByName(name){const n=normCity(name);return D.locations.find(r=>normCity(r.name)===n)}
function profileCounts(city){const m=MATRIX.ALL[normCity(city)]||{};return {CREADOR:m.CREADOR||0,GUIA:m.GUIA||0,AGENCIA:m.AGENCIA||0,PARTNER_LOCAL:m.PARTNER_LOCAL||0}}
function targetForCity(city){const isQ4=D.roadmap.some(r=>r.name===normCity(city)&&r.quarter==='Q4');const won=(rowByName(city)?.won||0)>0;return won||isQ4?10:6}
function stageClass(s){if(['ACTIVO','CREANDO_EXPERIENCIA','INTERESADO'].includes(s))return'green';if(['COLA_ENVIO','PREPARADO'].includes(s))return'amber';if(s==='PROSPECTO')return'purple';return''}
function featuredFor(city=null,country=null){let arr=FEATURED.slice();if(city)arr=arr.filter(x=>normCity(x.city)===normCity(city));else if(country){const cities=D.locations.filter(r=>r.country===country).map(r=>normCity(r.name));arr=arr.filter(x=>cities.includes(normCity(x.city)))}if(profile!=='ALL')arr=arr.filter(x=>x.type===profile);if(view==='SENT')arr=arr.filter(x=>x.stage==='ENVIADO');else if(view==='QUEUE')arr=arr.filter(x=>x.stage==='COLA_ENVIO');else if(view==='INTERESTED')arr=arr.filter(x=>x.stage==='INTERESADO');else if(view==='WON')arr=arr.filter(x=>['ACTIVO','CREANDO_EXPERIENCIA'].includes(x.stage));else if(view==='NEXT')arr=arr.filter(x=>x.next);return arr.sort((a,b)=>b.score-a.score)}
function renderHeroCity(name){const r=rowByName(name)||{name,country:'',total:0,sent:0,interested:0,won:0};const pcs=profileCounts(name),t=targetForCity(name),next=NEXT_CITY[normCity(name)]||0;document.getElementById('hero').innerHTML=`<div class="heroImage" style="background-image:url('${photo(name)}')"><div class="heroBadge">${view==='ROADMAP'?'ROADMAP':label().toUpperCase()}</div><div class="heroOverlay"><h2>${name}</h2><p>${r.country||''} · ${r.total||0} oportunidades CRM</p></div></div><div class="heroBody"><div class="cityMetrics"><div class="mBox"><span class="v">${r.total||0}<small class="obj">/ ${t}</small></span><span>CRM · objetivo</span></div><div class="mBox"><span class="v">${r.sent||0}<small class="obj">/ ${Math.ceil(t*.7)}</small></span><span>enviados · obj.</span></div><div class="mBox"><span class="v">${r.interested||0}<small class="obj">/ 2</small></span><span>interesados · obj.</span></div><div class="mBox"><span class="v">${r.won||0}<small class="obj">/ 1</small></span><span>conseguido · obj.</span></div><div class="mBox"><span class="v">${next}<small class="obj">/ ${Math.max(1,r.total||1)}</small></span><span>próx. pasos · 100%</span></div></div><div class="profileMix">${Object.entries(pcs).map(([k,v])=>`<span class="mix">${PTYPE[k]} <b>${v}</b> <span class="o">/ ${PGOAL[k]}</span></span>`).join('')}</div></div>`;
const cards=featuredFor(name);renderOpportunityCards(cards,`Perfiles con datos básicos en ${name}`);const top=cards[0];document.getElementById('detail').innerHTML=`<h3>Lectura del mercado</h3><p>${explainCity(r,pcs)}</p><div class="nextBox"><b>PRÓXIMO PASO PRIORITARIO</b><p>${top?top.next:(next?'Revisar las oportunidades con próxima acción y ejecutar por prioridad.':'Completar clasificación y activar nuevos perfiles de calidad.')}</p></div>`}
function explainCity(r,pcs){const lead=Object.entries(pcs).sort((a,b)=>b[1]-a[1])[0];const mix=lead&&lead[1]?`${PTYPE[lead[0]].toLowerCase()}s como perfil dominante`:'sin suficiente clasificación de perfil';return `${r.name} tiene ${r.total||0} oportunidades geolocalizadas y ${NEXT_CITY[normCity(r.name)]||0} con próximo paso activo. El mix actual muestra ${mix}. El objetivo local combina densidad, variedad de perfiles y al menos una experiencia real activa.`}
function renderCountry(name){const rr=D.locations.filter(r=>r.country===name),total=rr.reduce((a,r)=>a+r.total,0),sent=rr.reduce((a,r)=>a+(r.sent||0),0),intr=rr.reduce((a,r)=>a+(r.interested||0),0),won=rr.reduce((a,r)=>a+(r.won||0),0),nxt=rr.reduce((a,r)=>a+(NEXT_CITY[normCity(r.name)]||0),0);const best=rr.sort((a,b)=>b.total-a.total)[0];document.getElementById('hero').innerHTML=`<div class="heroImage" style="background-image:url('${photo(best?.name||'')}')"><div class="heroBadge">PAÍS / MERCADO</div><div class="heroOverlay"><h2>${name}</h2><p>${rr.length} ciudades con datos · ${total} oportunidades</p></div></div><div class="heroBody"><div class="cityMetrics"><div class="mBox"><span class="v">${total}</span><span>CRM</span></div><div class="mBox"><span class="v">${sent}</span><span>enviados</span></div><div class="mBox"><span class="v">${intr}</span><span>interesados</span></div><div class="mBox"><span class="v">${won}</span><span>conseguidos</span></div><div class="mBox"><span class="v">${nxt}</span><span>próx. pasos</span></div></div></div>`;const cards=featuredFor(null,name);renderOpportunityCards(cards,`Perfiles destacados en ${name}`);document.getElementById('detail').innerHTML=`<h3>Ciudades del mercado</h3><p>${rr.slice().sort((a,b)=>b.total-a.total).map(r=>`${r.name} · ${r.total}`).join(' · ')||'Sin ciudades normalizadas.'}</p><div class="nextBox"><b>OBJETIVO</b><p>Densificar las ciudades con señal real antes de abrir nuevos nodos y asegurar variedad entre creadores, guías, agencias y partners.</p></div>`}
function defaultVisual(){const cards=featuredFor().slice(0,12);const top=D.locations.slice().sort((a,b)=>metric(b)-metric(a))[0]||D.locations[0];if(top)renderHeroCity(top.name);renderOpportunityCards(cards,'Mejores oportunidades según el filtro actual')}
function renderOpportunityCards(cards,hint){document.getElementById('oppHint').textContent=hint||'';const el=document.getElementById('opportunities');if(!cards.length){el.innerHTML=`<div class="empty">No hay tarjetas detalladas para esta combinación. El mapa sigue mostrando el recuento completo del CRM sin inventar datos de contacto.</div>`;return}el.innerHTML=cards.slice(0,14).map(x=>`<article class="vCard" onclick="selectCity('${x.city.replaceAll("'","\\'")}')"><div class="vImg" style="background-image:url('${photo(x.city)}')"><div class="scoreBubble">${x.score}</div><div class="typeBadge">${PTYPE[x.type]||x.type}</div></div><div class="vBody"><h4>${x.name}</h4><div class="who">${x.person}${x.company?' · '+x.company:''}</div><div class="meta"><span class="tag ${stageClass(x.stage)}">${x.status}</span><span class="tag">${x.city}</span></div><div class="step"><b>Siguiente:</b> ${x.next}</div></div></article>`).join('')}
function renderRoad(){const arr=D.roadmap.filter(r=>quarter==='ALL'||r.quarter===quarter).sort((a,b)=>b.score-a.score);document.getElementById('roadCards').innerHTML=arr.slice(0,18).map(r=>`<article class="vCard roadCard" onclick="selectCity('${r.name.replaceAll("'","\\'")}',${JSON.stringify(r).replaceAll('"','&quot;')})"><div class="vImg" style="background-image:url('${photo(r.name)}')"><span class="quarterBadge">${r.quarter==='Q4'?'Q4 2026':r.quarter+' 2027'}</span><div class="scoreBubble">${r.score}</div></div><div class="vBody"><h4>${r.name}</h4><div class="who">${r.country}</div><div class="meta"><span class="tag">${r.quarter}</span><span class="tag green">Match ${r.score}</span></div></div></article>`).join('')}
function selectCity(name,road=null){selected={type:'city',name:normCity(name)};const r=rowByName(name);if(r)map.flyTo([r.lat,r.lng],Math.max(map.getZoom(),4),{duration:.6});else if(road)map.flyTo([road.lat,road.lng],4,{duration:.6});renderHeroCity(normCity(name))}
function selectCountry(name){selected={type:'country',name};const layers=[];countryLayer.eachLayer(l=>{const raw=l.feature?.properties?.name||l.feature?.properties?.ADMIN||'';if((ALIAS[raw]||raw)===name)layers.push(l)});if(layers.length){const g=L.featureGroup(layers);map.fitBounds(g.getBounds(),{padding:[20,20],maxZoom:4})}renderCountry(name)}
function renderLegend(){const items=view==='ROADMAP'?[['#2563eb','Q4 2026'],['#0f9f8f','Q1 2027'],['#e8a020','Q2 2027'],['#ea795f','Q3 2027']]:[[color(),label()],[ '#e5e7eb','sin actividad con este filtro']];document.getElementById('legend').innerHTML=items.map(x=>`<span><i style="background:${x[0]}"></i>${x[1]}</span>`).join('')}
function renderUnmapped(){const missing=SUMMARY.total-SUMMARY.mapped;document.getElementById('unmapped').innerHTML=`<div><b>CRM aún sin ciudad normalizada</b><p>No se dibujan ubicaciones inventadas. ODÍN debe completar esta capa desde evidencia real.</p></div><div class="big">${missing}<span style="font-size:10px;color:#98a2b3"> / obj. 0</span></div>`}
function refresh(fit=false){renderFilters();redrawCountries();redrawMarkers();renderLegend();document.getElementById('mode').textContent=label()+(profile!=='ALL'?' · '+PTYPE[profile]:'');document.getElementById('count').textContent=statCount()+' visibles';renderRoad();renderUnmapped();if(selected?.type==='city')renderHeroCity(selected.name);else if(selected?.type==='country')renderCountry(selected.name);else defaultVisual();if(fit){if(view==='ROADMAP'){const rr=D.roadmap.filter(r=>quarter==='ALL'||r.quarter===quarter);if(rr.length)map.fitBounds(L.latLngBounds(rr.map(r=>[r.lat,r.lng])),{padding:[35,35]})}else fitVisible()}}
function fitVisible(){const rr=rows();if(rr.length)map.fitBounds(L.latLngBounds(rr.map(r=>[r.lat,r.lng])),{padding:[35,35],maxZoom:4});else map.setView([22,10],2)}
function doSearch(){const q=document.getElementById('search').value.trim().toLowerCase();if(!q)return;const r=D.locations.find(x=>x.name.toLowerCase().includes(q)||x.country.toLowerCase().includes(q));if(r){selectCity(r.name);return}const rd=D.roadmap.find(x=>x.name.toLowerCase().includes(q)||x.country.toLowerCase().includes(q));if(rd)selectCity(rd.name,rd)}
document.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});document.getElementById('clearBtn').onclick=()=>{document.getElementById('search').value='';selected=null;refresh(true)};document.getElementById('worldBtn').onclick=()=>{selected=null;map.setView([22,10],2);defaultVisual()};document.getElementById('fullBtn').onclick=async()=>{const el=document.getElementById('focus');try{if(!document.fullscreenElement){await el.requestFullscreen();setTimeout(()=>map.invalidateSize(),150)}else await document.exitFullscreen()}catch(e){window.open(location.href,'_blank')}};document.addEventListener('fullscreenchange',()=>setTimeout(()=>map.invalidateSize(),120));
Promise.all([fetch(DATA_URL).then(r=>r.json()),fetch(GEO_URL).then(r=>r.json()),fetch(INTEL_URL).then(r=>r.json())]).then(([d,g,i])=>{D=d;geo=g;SUMMARY=i.summary;TARGETS=i.targets;MATRIX=i.matrices;NEXT_CITY=i.nextCity;FEATURED=i.featured;renderStats();document.getElementById('sync').textContent='● CRM · '+SUMMARY.total+' oportunidades';refresh();map.setView([22,10],2)}).catch(e=>{document.getElementById('sync').textContent='Error de datos';document.getElementById('detail').innerHTML='<h3>No se pudo cargar el mapa</h3><p>'+String(e)+'</p>'});