(()=>{
const SNAPSHOT='11 Sep 2026 · 245 oportunidades';
const LIVE_SUMMARY={total:245,mapped:112,unmapped:133,supply:158,partners:52,institutions:18,contests:14,capital:2,sent:124,queue:57,interested:21,won:3,next:239,creators:28,guides:86,agencies:43,activeConversations:19,pendingApproval:177,p0:170};
const TOTAL={'Barcelona':13,'Roma':10,'Budapest':8,'Londres':7,'Madrid':7,'París':7,'Dublín':6,'Tokio':5,'Toledo':5,'Berlín':5,'Estambul':4,'Dubrovnik':4,'Praga':4,'Cracovia':4,'Oporto':3,'Ámsterdam':2,'Cartago':1,'Florencia':1,'Granada':1,'España · ámbito nacional':1,'Badalona':1,'València':1,'Medellín':1,'Lloret de Mar':1,'Salou':1,'Murcia':1,'Sevilla':1,'Tenerife':1,'Costa Brava / Girona':1,'Viena':1,'Lisboa':1,'Glasgow':1,'Alemania · ámbito nacional':1,'Sitges':1};
const SENT={'Budapest':6,'Londres':6,'Roma':5,'Madrid':5,'Toledo':4,'Tokio':4,'París':4,'Estambul':3,'Dublín':3,'Cracovia':3,'Barcelona':3,'Berlín':2,'Dubrovnik':1,'Costa Brava / Girona':1,'Sitges':1,'Ámsterdam':1,'Badalona':1,'València':1,'Cartago':1,'Salou':1,'Lloret de Mar':1,'Praga':1,'Glasgow':1,'Tenerife':1,'Granada':1};
const QUEUE={'Dublín':2,'París':2,'Roma':2,'Budapest':1,'Oporto':1,'Florencia':1,'Cracovia':1,'Praga':1,'Dubrovnik':1,'Alemania · ámbito nacional':1,'Londres':1,'Lisboa':1,'Viena':1,'Berlín':1,'Ámsterdam':1,'Madrid':1,'Barcelona':1,'España · ámbito nacional':1};
const INTEREST={'Roma':2,'Dubrovnik':1,'Madrid':1,'Barcelona':1,'Oporto':1,'Tokio':1,'Medellín':1,'Budapest':1};
const RESPONSES={'Budapest':1,'Dubrovnik':1,'Madrid':1,'Barcelona':1,'París':1,'Roma':1,'Oporto':1};
const WON={'Barcelona':1,'Medellín':1,'Tokio':1};
const NEXT={'Barcelona':13,'Roma':10,'Budapest':8,'París':7,'Madrid':7,'Londres':7,'Dublín':6,'Toledo':5,'Tokio':5,'Estambul':4,'Dubrovnik':4,'Berlín':4,'Praga':4,'Cracovia':4,'Ámsterdam':2,'Oporto':2,'Cartago':1,'Florencia':1,'Granada':1,'España · ámbito nacional':1,'Badalona':1,'València':1,'Medellín':1,'Lloret de Mar':1,'Salou':1,'Murcia':1,'Sevilla':1,'Tenerife':1,'Costa Brava / Girona':1,'Glasgow':1,'Lisboa':1,'Alemania · ámbito nacional':1,'Sitges':1,'Viena':1};
const P0={'Roma':8,'Barcelona':7,'Londres':6,'París':6,'Madrid':5,'Budapest':4,'Dublín':4,'Cracovia':4,'Estambul':3,'Berlín':3,'Toledo':2,'Lisboa':1,'Florencia':1,'Viena':1,'Cartago':1,'Tokio':1,'Ámsterdam':1,'Granada':1,'Badalona':1,'Oporto':1,'València':1,'Medellín':1,'Salou':1,'Praga':1,'Lloret de Mar':1,'Sevilla':1,'Tenerife':1,'Costa Brava / Girona':1,'Dubrovnik':1,'Sitges':1,'Alemania · ámbito nacional':1};
const P1={'Barcelona':4,'Budapest':4,'Tokio':4,'Dubrovnik':2,'Toledo':2,'Madrid':2,'Londres':1,'Ámsterdam':1,'Dublín':1,'Estambul':1,'España · ámbito nacional':1,'Oporto':1,'Roma':1,'Praga':1,'París':1};
const P2={'Glasgow':1,'Murcia':1};
const P3={'Barcelona':1};
const RECENT7={'Londres':5,'Roma':5,'Madrid':4,'Toledo':4,'Budapest':4,'París':4,'Dublín':4,'Tokio':4,'Estambul':3,'Dubrovnik':3,'Cracovia':3,'Barcelona':2,'Berlín':2,'Costa Brava / Girona':1,'Tenerife':1,'Lloret de Mar':1,'Oporto':1,'Granada':1,'Glasgow':1,'Cartago':1,'Badalona':1,'Salou':1,'Praga':1};
const RECENT30={...RECENT7,Barcelona:3,Medellín:1};
const CREATOR={'Barcelona':4,'Londres':3,'Roma':3,'Tokio':3,'París':2,'Madrid':2,'Toledo':1,'Estambul':1,'Murcia':1};
const GUIDE={'Budapest':6,'Berlín':4,'Dublín':4,'Estambul':3,'Dubrovnik':3,'Londres':3,'Cracovia':3,'Roma':3,'París':3,'Madrid':2,'Toledo':2,'Glasgow':1,'Oporto':1,'Praga':1,'Ámsterdam':1,'Barcelona':1};
const AGENCY={'Madrid':2,'Tokio':2,'Roma':2,'Praga':2,'Toledo':1,'Granada':1,'Budapest':1,'Oporto':1,'Cartago':1,'Medellín':1};
const PARTNER={'Barcelona':6,'Dublín':2,'Roma':1,'París':1,'Londres':1,'Viena':1,'Berlín':1,'Ámsterdam':1,'España · ámbito nacional':1,'Florencia':1};
const SUPPLY={'Roma':8,'Budapest':7,'Londres':6,'Madrid':6,'Barcelona':5,'Toledo':5,'París':5,'Tokio':5,'Estambul':4,'Berlín':4,'Dublín':4,'Cracovia':3,'Praga':3,'Dubrovnik':3,'Oporto':2,'Ámsterdam':1,'Murcia':1,'Granada':1,'Glasgow':1,'Cartago':1,'Medellín':1};
const INSTITUTION={'Badalona':1,'Barcelona':1,'Budapest':1,'Costa Brava / Girona':1,'Dubrovnik':1,'Alemania · ámbito nacional':1,'Cracovia':1,'Lisboa':1,'Lloret de Mar':1,'Madrid':1,'Oporto':1,'París':1,'Praga':1,'Roma':1,'Salou':1,'Sitges':1,'Tenerife':1,'València':1};
const CAPITAL={'Barcelona':1}; const CONTEST={'Sevilla':1};
const LIVE_FEATURED=[
{city:'Roma',type:'GUIA',name:'Francesca The Guide',person:'Francesca Rossi Pantoja',company:'Francesca The Guide',score:97,priority:'P0',stage:'ENVIADO',status:'FU1 pendiente',next:'Revisar y aprobar el follow-up vigente; no enviar antes de su fecha.'},
{city:'Roma',type:'INSTITUCION',name:'Roma Capitale Tourism',person:'Fabio Pacciani',company:'Roma Capitale',score:97,priority:'P0',stage:'COLA_ENVIO',status:'Institución · pendiente QA',next:'QA del primer contacto institucional y aprobación humana.'},
{city:'Barcelona',type:'GUIA',name:'Barcelona Routes',person:'Cristina Monjo',company:'Barcelona Routes',score:86,priority:'P1',stage:'RESPONDIO',status:'Conversación activa',next:'Continuar únicamente desde el hilo real; cold follow-up detenido.'},
{city:'Barcelona',type:'PARTNER_LOCAL',name:'Barna Centre',person:'Federació Barna Centre',company:'Barnacentre',score:94,priority:'P0',stage:'COLA_ENVIO',status:'Partner · seguimiento',next:'Seguimiento histórico breve sin repetir el primer pitch.'},
{city:'Medellín',type:'AGENCIA',name:"Let's Walk Medellín",person:"Let's Walk Medellín",company:"Let's Walk Medellín",score:96,priority:'P0',stage:'CREANDO_EXPERIENCIA',status:'Conseguido · onboarding',next:'Desbloquear onboarding y llevar la primera experiencia a publicación.'},
{city:'Tokio',type:'CREADOR',name:'AKIBA OTAKU',person:'Nao Koiwa',company:'AKIBA OTAKU',score:99,priority:'P0',stage:'ENVIADO',status:'FU1 pendiente',next:'Revisar y aprobar el follow-up vigente.'},
{city:'Tokio',type:'CREADOR',name:'Tokyo Kenchan',person:'Kengo',company:'Tokyo Kenchan',score:97,priority:'P1',stage:'ENVIADO',status:'FU1 pendiente',next:'Respetar la fecha de seguimiento y priorizar por respuesta.'},
{city:'Budapest',type:'GUIA',name:'Kata Budapest',person:'Kata',company:'Kata Budapest',score:98,priority:'P0',stage:'ENVIADO',status:'FU1 pendiente',next:'Revisar y aprobar el follow-up vigente.'},
{city:'Madrid',type:'GUIA',name:'Madrid Museum Tours',person:'Hernan A. Satt',company:'Madrid Museum Tours',score:95,priority:'P0',stage:'ENVIADO',status:'FU1 pendiente',next:'Revisar y aprobar el follow-up vigente.'},
{city:'Londres',type:'GUIA',name:'Gavin with a G',person:'Gavin',company:'Gavin with a G',score:95,priority:'P0',stage:'ENVIADO',status:'FU1 pendiente',next:'Revisar y aprobar el follow-up vigente.'},
{city:'Londres',type:'PARTNER_LOCAL',name:'London & Partners',person:'General enquiries',company:'London & Partners',score:96,priority:'P0',stage:'COLA_ENVIO',status:'Partner · pendiente QA',next:'QA del primer cold y aprobación humana.'},
{city:'París',type:'GUIA',name:'Hugo Loyon',person:'Hugo Loyon',company:'Hugo Loyon',score:93,priority:'P0',stage:'ENVIADO',status:'FU1 pendiente',next:'Revisar y aprobar el follow-up vigente.'},
{city:'París',type:'PARTNER_LOCAL',name:'Choose Paris Region',person:'Open Innovation',company:'Choose Paris Region',score:95,priority:'P0',stage:'COLA_ENVIO',status:'Partner · pendiente QA',next:'QA del primer cold y aprobación humana.'},
{city:'Dublín',type:'GUIA',name:"Pat Liddy's Walking Tours",person:'Pat Liddy',company:"Pat Liddy's Walking Tours of Dublin",score:98,priority:'P3',stage:'NEVERA',status:'Nurturing · invierno',next:'Retomar a principios de invierno tal como pidió el lead.'}
];
let v11Priority='P0',v11Activity='ALL';
function mapVal(map,name){return map[name]||0}
function patchData(){
  Object.assign(SUMMARY,LIVE_SUMMARY);Object.assign(D.summary||{},LIVE_SUMMARY);Object.assign(TARGETS,{total:300,mapped:245,sent:150,queueMax:30,interested:25,won:10,creators:40,guides:100,agencies:60,partners:60});
  PTYPE.INSTITUCION='Institución'; COLORS.PRIORITY='#c2413a'; COLORS.ACTIVITY='#2f6fec';
  D.locations.forEach(r=>{const n=normCity(r.name);r.total=mapVal(TOTAL,n);r.sent=mapVal(SENT,n);r.queue=mapVal(QUEUE,n);r.interested=mapVal(INTEREST,n);r.responses=mapVal(RESPONSES,n);r.won=mapVal(WON,n);r.next=mapVal(NEXT,n);r.p0=mapVal(P0,n);r.p1=mapVal(P1,n);r.p2=mapVal(P2,n);r.p3=mapVal(P3,n);r.recent7=mapVal(RECENT7,n);r.recent30=mapVal(RECENT30,n);r.supply=mapVal(SUPPLY,n);r.partners=mapVal(PARTNER,n);r.institutions=mapVal(INSTITUTION,n);r.capital=mapVal(CAPITAL,n);r.contests=mapVal(CONTEST,n)});
  MATRIX.ALL={};D.locations.forEach(r=>{const n=normCity(r.name);MATRIX.ALL[n]={CREADOR:mapVal(CREATOR,n),GUIA:mapVal(GUIDE,n),AGENCIA:mapVal(AGENCY,n),PARTNER_LOCAL:mapVal(PARTNER,n)}});
  Object.keys(NEXT).forEach(k=>NEXT_CITY[k]=NEXT[k]);
  const seen=new Set();FEATURED=[...LIVE_FEATURED,...FEATURED].filter(x=>{const k=(x.name+'|'+x.city).toLowerCase();if(seen.has(k))return false;seen.add(k);return true});
  D.locations.forEach(r=>{const s=marketScore(r);r.marketScore=s.score;r.marketFactors=s.factors;r.marketState=marketState(r)});
}
function marketScore(r){const pcs=profileCounts(r.name),diversity=Object.values(pcs).filter(Boolean).length;const density=Math.min(20,(r.total/10)*20);const conv=r.sent?Math.min(25,(r.interested/r.sent)/.25*25):0;const response=Math.min(10,(r.responses||0)*10);const won=(r.won||0)>0?25:0;const next=Math.min(10,(r.next/Math.max(1,r.total))*10);const mix=(diversity/4)*5;const momentum=Math.min(5,(r.recent7/Math.max(1,r.total))*5);return{score:Math.round(density+conv+response+won+next+mix+momentum),factors:{Densidad:Math.round(density),Conversión:Math.round(conv),Respuesta:Math.round(response),Conseguido:Math.round(won),Ejecución:Math.round(next),Mix:Math.round(mix),Momentum:Math.round(momentum)}}}
function marketState(r){if((r.won||0)>0)return'CONSEGUIDA';if((r.responses||0)>0||(r.interested||0)>0)return'ACTUAR AHORA';if((r.sent||0)>=3&&(r.interested||0)===0)return'OPTIMIZAR';if((r.total||0)>=5)return'DENSIFICAR';if((r.recent30||0)===0)return'NURTURING';return'EXPLORAR'}
function stateClass(s){return s==='CONSEGUIDA'?'won':s==='ACTUAR AHORA'?'now':s==='OPTIMIZAR'?'optimize':s==='DENSIFICAR'?'densify':s==='NURTURING'?'nurture':'explore'}
function nextBestAction(r){if((r.responses||0)>0)return'Atender primero la conversación real y detener cualquier cold paralelo. Convertir la señal en un siguiente compromiso concreto.';if((r.interested||0)>0)return'Cerrar el siguiente paso con los interesados antes de ampliar volumen en esta ciudad.';if((r.won||0)>0)return'Usar el caso conseguido como prueba social y densificar con perfiles complementarios alrededor del mercado.';if((r.sent||0)>=3&&(r.interested||0)===0)return'No aumentar volumen a ciegas: revisar segmentación, propuesta y aprendizaje de los envíos antes de seguir disparando.';if((r.queue||0)>0)return'Desbloquear QA/aprobación de las mejores oportunidades de la cola y lanzar solo las que tengan mayor encaje.';return'Añadir perfiles de alta calidad y variedad hasta crear densidad suficiente para validar el mercado.'}
function mountUI(){
  document.querySelector('.head p').textContent='CRM real · inteligencia de mercado · decisiones · expansión global';document.getElementById('sync').textContent='● '+SNAPSHOT;
  const stats=document.getElementById('stats');const ribbon=document.createElement('div');ribbon.id='intelRibbon';ribbon.className='intelRibbon';stats.insertAdjacentElement('afterend',ribbon);
  const firstLabel=document.querySelector('.focus > .label');if(firstLabel)firstLabel.textContent='Decisión comercial';
  const views=document.getElementById('views');const details=document.createElement('details');details.className='advancedFilters';details.id='advancedFilters';details.innerHTML='<summary>Más filtros y diagnóstico <span class="smartHint">perfil · funnel · prioridad · actividad</span></summary><div class="advancedBody"><div class="advancedRow" id="advancedStates"><div class="label">Otras vistas</div><div class="miniPills" id="extraStates"></div></div><div class="advancedRow" id="priorityRow"><div class="label">Prioridad operativa</div><div class="miniPills" id="priorityPills"></div></div><div class="advancedRow" id="activityRow"><div class="label">Actividad comercial</div><div class="miniPills" id="activityPills"></div><div class="filterNote">La ventana temporal muestra contactos con actividad registrada en la ciudad.</div></div></div>';views.insertAdjacentElement('afterend',details);
  const body=details.querySelector('.advancedBody');body.appendChild(document.getElementById('profileBox'));body.appendChild(document.getElementById('funnelBox'));
  const radar=document.createElement('section');radar.className='radarSection';radar.id='gapRadar';radar.innerHTML='<div class="sectionTitle"><h3>Radar de gaps</h3><small>qué frena la expansión ahora</small></div><div class="radarGrid" id="radarGrid"></div>';document.querySelector('.visualPanel').insertAdjacentElement('afterend',radar);
  document.getElementById('search').placeholder='Buscar ciudad, país, creador, guía, agencia, empresa o contacto…';
}
function renderExecutiveIntel(){const top=D.locations.filter(r=>r.total>0&&r.scope!=='country').slice().sort((a,b)=>actionRank(b)-actionRank(a))[0];const mapPct=Math.round(SUMMARY.mapped/SUMMARY.total*100),approvalPct=Math.round(SUMMARY.pendingApproval/SUMMARY.total*100),p0Pct=Math.round(SUMMARY.p0/SUMMARY.total*100),conv=Math.round(SUMMARY.interested/Math.max(1,SUMMARY.sent)*100);document.getElementById('intelRibbon').innerHTML=`<div class="intelCard primary"><span class="intelDot"></span><div class="intelEyebrow">Decisión recomendada</div><div class="intelValue">${top?top.name:'—'}</div><div class="intelTitle">${top?top.marketState:'Sin señal'}</div><div class="intelText">${top?nextBestAction(top):'Completar datos del CRM.'}</div></div><div class="intelCard alert"><div class="intelEyebrow">Cuello de botella</div><div class="intelValue">${SUMMARY.pendingApproval} <small style="font-size:10px">${approvalPct}%</small></div><div class="intelTitle">pendientes de aprobación</div><div class="intelText">La atención humana es ahora el principal cuello de botella operativo.</div></div><div class="intelCard warn"><div class="intelEyebrow">Calidad de prioridad</div><div class="intelValue">${SUMMARY.p0} <small style="font-size:10px">${p0Pct}%</small></div><div class="intelTitle">marcados P0</div><div class="intelText">P0 está demasiado poblado para discriminar. El score de mercado añade una segunda capa de decisión.</div></div><div class="intelCard"><div class="intelEyebrow">Tracción / datos</div><div class="intelValue">${conv}% <small style="font-size:10px">interés/outreach</small></div><div class="intelTitle">${SUMMARY.mapped}/${SUMMARY.total} geolocalizadas · ${mapPct}%</div><div class="intelText">${SUMMARY.activeConversations} conversaciones activas · ${SUMMARY.won} mercados conseguidos.</div></div>`}
function actionRank(r){return (r.responses||0)*35+(r.interested||0)*22+(r.p0||0)*4+(r.queue||0)*2+(r.recent7||0)*2+(r.marketScore||0)/5}
const baseOldMetric=oldMetric,baseColor=color,baseLabel=label,baseFeaturedFor=featuredFor;
oldMetric=function(r){if(view==='PRIORITY')return r[v11Priority.toLowerCase()]||0;if(v11Activity==='7D')return r.recent7||0;if(v11Activity==='30D')return r.recent30||0;return baseOldMetric(r)};
profileMetric=function(city){city=normCity(city);if(profile==='ALL')return null;return MATRIX.ALL?.[city]?.[profile]||0};
metric=function(r){if(view==='ROADMAP')return 0;if(view==='PRIORITY')return r[v11Priority.toLowerCase()]||0;if(v11Activity!=='ALL')return v11Activity==='7D'?(r.recent7||0):(r.recent30||0);if(profile!=='ALL')return profileMetric(r.name);return oldMetric(r)};
label=function(){if(view==='PRIORITY')return'Prioridad '+v11Priority;if(v11Activity==='7D')return'Actividad · 7 días';if(v11Activity==='30D')return'Actividad · 30 días';return baseLabel()};
color=function(){if(view==='PRIORITY')return v11Priority==='P0'?'#c2413a':v11Priority==='P1'?'#d97706':v11Priority==='P2'?'#2563eb':'#64748b';if(v11Activity!=='ALL')return'#2f6fec';return baseColor()};
featuredFor=function(city=null,country=null){let arr=FEATURED.slice();if(city)arr=arr.filter(x=>normCity(x.city)===normCity(city));else if(country){const cities=D.locations.filter(r=>r.country===country).map(r=>normCity(r.name));arr=arr.filter(x=>cities.includes(normCity(x.city)))}if(view==='PRIORITY')arr=arr.filter(x=>x.priority===v11Priority);if(profile!=='ALL')arr=arr.filter(x=>x.type===profile);if(view==='SENT')arr=arr.filter(x=>x.stage==='ENVIADO');else if(view==='QUEUE')arr=arr.filter(x=>x.stage==='COLA_ENVIO');else if(view==='INTERESTED')arr=arr.filter(x=>['INTERESADO','RESPONDIO'].includes(x.stage));else if(view==='WON')arr=arr.filter(x=>['ACTIVO','CREANDO_EXPERIENCIA','REUNION_AGENDADA'].includes(x.stage));else if(view==='NEXT')arr=arr.filter(x=>x.next);return arr.sort((a,b)=>(b.priority==='P0')-(a.priority==='P0')||b.score-a.score)};
renderStats=function(){const citiesWon=new Set(D.locations.filter(r=>r.won>0).map(r=>normCity(r.name))).size,countriesWon=new Set(D.locations.filter(r=>r.won>0).map(r=>r.country)).size;document.getElementById('stats').innerHTML=[goalStat('Oportunidades CRM',SUMMARY.total,TARGETS.total),goalStat('Con destino geográfico',SUMMARY.mapped,SUMMARY.total,'','Obj. 100%'),goalStat('Outreach lanzado',SUMMARY.sent,TARGETS.sent,'good'),goalStat('Interesados / avanzados',SUMMARY.interested,TARGETS.interested,'good'),goalStat('Ciudades conseguidas',citiesWon,10,'purple'),goalStat('Países conseguidos',countriesWon,20,'purple'),goalStat('Con próximo paso',SUMMARY.next,SUMMARY.total,'good','Obj. 100%'),goalStat('Conversaciones activas',SUMMARY.activeConversations,25,'good')].join('')};
renderFilters=function(){const primary=[['PRIORITY','Prioridad ahora',SUMMARY.p0,'P0'],['SENT','Outreach',SUMMARY.sent,'/'+TARGETS.sent],['INTERESTED','Interés',SUMMARY.interested,'/'+TARGETS.interested],['WON','Conseguido',SUMMARY.won,'/10 ciudades'],['ROADMAP','Roadmap 12M',D?.roadmap?.length||36,'']];document.getElementById('views').innerHTML=primary.map(x=>`<button class="pill ${view===x[0]?'active':''}" data-view="${x[0]}">${x[1]} <span class="count">${x[2]}</span>${x[3]?`<span class="target">${x[3]}</span>`:''}</button>`).join('');
const extras=[['ALL','Todo CRM',SUMMARY.total],['QUEUE','Preparados / cola',SUMMARY.queue],['NEXT','Próximos pasos',SUMMARY.next]];document.getElementById('extraStates').innerHTML=extras.map(x=>`<button class="miniPill ${view===x[0]&&v11Activity==='ALL'?'active':''}" data-extra="${x[0]}">${x[1]} · ${x[2]}</button>`).join('');
const pp=[['P0',P0],['P1',P1],['P2',P2],['P3',P3]];const pTotals={P0:SUMMARY.p0,P1:Object.values(P1).reduce((a,b)=>a+b,0)+20,P2:3,P3:2};document.getElementById('priorityPills').innerHTML=pp.map(([k])=>`<button class="miniPill ${k.toLowerCase()} ${view==='PRIORITY'&&v11Priority===k?'active':''}" data-priority="${k}">${k} · ${pTotals[k]}</button>`).join('');
document.getElementById('activityPills').innerHTML=[['ALL','Todo'],['7D','7 días'],['30D','30 días']].map(x=>`<button class="miniPill ${v11Activity===x[0]?'active':''}" data-activity="${x[0]}">${x[1]}</button>`).join('');
const p=[['ALL','Todos',SUMMARY.creators+SUMMARY.guides+SUMMARY.agencies+SUMMARY.partners,''],['CREADOR','Creadores',SUMMARY.creators,'/'+TARGETS.creators],['GUIA','Guías',SUMMARY.guides,'/'+TARGETS.guides],['AGENCIA','Agencias',SUMMARY.agencies,'/'+TARGETS.agencies],['PARTNER_LOCAL','Partners',SUMMARY.partners,'/'+TARGETS.partners]];document.getElementById('profiles').innerHTML=p.map(x=>`<button class="pill profilePill ${profile===x[0]?'active':''}" data-profile="${x[0]}">${x[1]} <span class="count">${x[2]}</span><span class="target">${x[3]}</span></button>`).join('');
const fs=[['ALL','Todos'],['SUPPLY','Experiencias'],['PARTNER','Partners'],['INSTITUTION','Instituciones'],['CAPITAL','Capital'],['CONTEST','Concursos']];document.getElementById('funnels').innerHTML=fs.map(x=>`<button class="pill ${funnel===x[0]?'active':''}" data-funnel="${x[0]}">${x[1]}</button>`).join('');const qs=[['ALL','12 meses'],['Q4','Q4 2026'],['Q1','Q1 2027'],['Q2','Q2 2027'],['Q3','Q3 2027']];document.getElementById('quarters').innerHTML=qs.map(x=>`<button class="pill ${quarter===x[0]?'active':''}" data-quarter="${x[0]}">${x[1]}</button>`).join('');document.getElementById('quarterBox').style.display=view==='ROADMAP'?'block':'none';document.getElementById('advancedFilters').style.display=view==='ROADMAP'?'none':'block';
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;profile='ALL';funnel='ALL';v11Activity='ALL';if(view==='ROADMAP')profile='ALL';selected=null;refresh(true)});document.querySelectorAll('[data-extra]').forEach(b=>b.onclick=()=>{view=b.dataset.extra;profile='ALL';funnel='ALL';v11Activity='ALL';selected=null;refresh(true)});document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{profile=b.dataset.profile;view='ALL';funnel='ALL';v11Activity='ALL';selected=null;refresh(true)});document.querySelectorAll('[data-funnel]').forEach(b=>b.onclick=()=>{funnel=b.dataset.funnel;view='ALL';profile='ALL';v11Activity='ALL';selected=null;refresh(true)});document.querySelectorAll('[data-priority]').forEach(b=>b.onclick=()=>{v11Priority=b.dataset.priority;view='PRIORITY';profile='ALL';funnel='ALL';v11Activity='ALL';selected=null;refresh(true)});document.querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>{v11Activity=b.dataset.activity;view='ALL';profile='ALL';funnel='ALL';selected=null;refresh(true)});document.querySelectorAll('[data-quarter]').forEach(b=>b.onclick=()=>{quarter=b.dataset.quarter;selected=null;refresh(true)})};
function factorHtml(r){const f=r.marketFactors||{};const max={Densidad:20,Conversión:25,Respuesta:10,Conseguido:25,Ejecución:10,Mix:5,Momentum:5};return Object.entries(f).map(([k,v])=>`<div class="factorBar"><span>${k}</span><div class="factorTrack"><i style="width:${Math.min(100,v/Math.max(1,max[k])*100)}%"></i></div><em>${v}</em></div>`).join('')}
renderHeroCity=function(name){const r=rowByName(name)||{name,country:'',total:0,sent:0,interested:0,won:0,next:0,marketScore:0,marketState:'EXPLORAR',marketFactors:{}},pcs=profileCounts(name),t=targetForCity(name);document.getElementById('hero').innerHTML=`<div class="heroImage" style="background-image:url('${photo(name)}')"><div class="heroBadge">${view==='ROADMAP'?'ROADMAP':label().toUpperCase()}</div><div class="heroOverlay"><h2>${name}</h2><p>${r.country||''} · ${r.total||0} oportunidades CRM</p><div class="marketInline"><span class="marketBadge ${stateClass(r.marketState)}">${r.marketState}</span><span class="scoreInline">Market Score ${r.marketScore||0}/100</span></div></div></div><div class="heroBody"><div class="cityMetrics v11"><div class="mBox"><span class="v">${r.total||0}<small class="obj">/ ${t}</small></span><span>CRM · objetivo</span></div><div class="mBox"><span class="v">${r.sent||0}<small class="obj">/ ${Math.ceil(t*.7)}</small></span><span>outreach · obj.</span></div><div class="mBox attention"><span class="v">${r.responses||0}</span><span>conversaciones</span></div><div class="mBox"><span class="v">${r.interested||0}<small class="obj">/ 2</small></span><span>interés · obj.</span></div><div class="mBox emphasis"><span class="v">${r.won||0}<small class="obj">/ 1</small></span><span>conseguido · obj.</span></div><div class="mBox"><span class="v">${r.next||0}<small class="obj">/ ${Math.max(1,r.total||1)}</small></span><span>próx. pasos</span></div></div><div class="profileMix">${Object.entries(pcs).map(([k,v])=>`<span class="mix ${v===0?'gap':''}">${PTYPE[k]} <b>${v}</b> <span class="o">/ ${PGOAL[k]}</span></span>`).join('')}</div><div class="intelligenceRow"><div class="scoreRing" style="--score:${r.marketScore||0}"><strong>${r.marketScore||0}</strong><small>MARKET SCORE</small></div><div class="intelExplain"><b>Touryteller Market Intelligence</b><p>Score determinista del CRM: densidad, conversión, respuestas, consecución, ejecución, diversidad de perfiles y momentum.</p>${factorHtml(r)}</div></div></div>`;const cards=featuredFor(name);renderOpportunityCards(cards,`Siguiente acción y perfiles en ${name}`);document.getElementById('detail').innerHTML=`<h3>Decisión de mercado</h3><p>${explainCity(r,pcs)}</p><div class="decisionBox"><span class="kicker">Next Best Action</span><b>${r.marketState}</b><p>${nextBestAction(r)}</p></div>`};
explainCity=function(r,pcs){const diversity=Object.values(pcs).filter(Boolean).length,conv=r.sent?Math.round(r.interested/r.sent*100):0;return `${r.name} concentra ${r.total||0} oportunidades, ${r.p0||0} P0, ${r.responses||0} conversaciones activas y ${r.interested||0} señales de interés/avance. Conversión visible outreach→interés: ${conv}%. Mix comercial: ${diversity}/4 perfiles clave cubiertos. Próximo paso informado en ${r.next||0}/${r.total||0}.`};
renderCountry=function(name){const rr=D.locations.filter(r=>r.country===name&&r.scope!=='country'),total=rr.reduce((a,r)=>a+r.total,0),sent=rr.reduce((a,r)=>a+r.sent,0),intr=rr.reduce((a,r)=>a+r.interested,0),resp=rr.reduce((a,r)=>a+r.responses,0),won=rr.reduce((a,r)=>a+r.won,0),p0=rr.reduce((a,r)=>a+r.p0,0),avg=rr.length?Math.round(rr.reduce((a,r)=>a+r.marketScore,0)/rr.length):0,best=rr.slice().sort((a,b)=>actionRank(b)-actionRank(a))[0];document.getElementById('hero').innerHTML=`<div class="heroImage" style="background-image:url('${photo(best?.name||'')}')"><div class="heroBadge">PAÍS / MERCADO</div><div class="heroOverlay"><h2>${name}</h2><p>${rr.length} ciudades · ${total} oportunidades · Market Score medio ${avg}</p></div></div><div class="heroBody"><div class="cityMetrics v11"><div class="mBox"><span class="v">${total}</span><span>CRM</span></div><div class="mBox"><span class="v">${sent}</span><span>outreach</span></div><div class="mBox attention"><span class="v">${resp}</span><span>conversaciones</span></div><div class="mBox"><span class="v">${intr}</span><span>interés</span></div><div class="mBox emphasis"><span class="v">${won}</span><span>conseguido</span></div><div class="mBox"><span class="v">${p0}</span><span>P0</span></div></div></div>`;const cards=featuredFor(null,name);renderOpportunityCards(cards,`Perfiles destacados en ${name}`);document.getElementById('detail').innerHTML=`<h3>Lectura del país</h3><p>${rr.slice().sort((a,b)=>actionRank(b)-actionRank(a)).map(r=>`${r.name} · ${r.marketScore} · ${r.marketState}`).join(' · ')||'Sin ciudades normalizadas.'}</p><div class="decisionBox"><span class="kicker">Mercado prioritario</span><b>${best?.name||'—'}</b><p>${best?nextBestAction(best):'Completar la capa geográfica.'}</p></div>`};
renderOpportunityCards=function(cards,hint){document.getElementById('oppHint').textContent=hint||'';const el=document.getElementById('opportunities');if(!cards.length){el.innerHTML='<div class="empty">No hay fichas detalladas fiables para esta combinación. El mapa conserva los recuentos completos del CRM sin inventar datos.</div>';return}el.innerHTML=cards.slice(0,16).map((x,i)=>`<article class="vCard" data-v11-card="${i}"><div class="vImg" style="background-image:url('${photo(x.city)}')"><div class="scoreBubble">${x.score}</div><div class="typeBadge">${PTYPE[x.type]||x.type}</div></div><div class="vBody"><h4>${x.name}</h4><div class="who">${x.person||''}${x.company?' · '+x.company:''}</div><div class="meta">${x.priority?`<span class="tag ${x.priority==='P0'?'amber':''}">${x.priority}</span>`:''}<span class="tag ${stageClass(x.stage)}">${x.status}</span><span class="tag">${x.city}</span></div><div class="step"><b>Siguiente:</b> ${x.next||'Revisar próxima acción en CRM.'}</div></div></article>`).join('');el.querySelectorAll('[data-v11-card]').forEach((node,i)=>node.onclick=()=>selectCity(cards[i].city))};
defaultVisual=function(){const rr=D.locations.filter(r=>metric(r)>0&&r.scope!=='country').slice().sort((a,b)=>view==='PRIORITY'?actionRank(b)-actionRank(a):metric(b)-metric(a)),top=rr[0]||D.locations[0];if(top)renderHeroCity(top.name);renderOpportunityCards(featuredFor().slice(0,14),view==='PRIORITY'?'Oportunidades explícitamente priorizadas en CRM':'Mejores oportunidades según el filtro actual')};
renderLegend=function(){let items;if(view==='ROADMAP')items=[['#2563eb','Q4 2026'],['#0f9f8f','Q1 2027'],['#e8a020','Q2 2027'],['#ea795f','Q3 2027']];else if(view==='PRIORITY')items=[[color(),v11Priority+' activa'],['#e5e7eb','sin '+v11Priority]];else if(v11Activity!=='ALL')items=[['#2f6fec',label()],['#e5e7eb','sin actividad registrada']];else items=[[color(),label()],['#e5e7eb','sin actividad con este filtro']];document.getElementById('legend').innerHTML=items.map(x=>`<span><i style="background:${x[0]}"></i>${x[1]}</span>`).join('')};
renderUnmapped=function(){const missing=SUMMARY.total-SUMMARY.mapped,p=Math.round(SUMMARY.mapped/SUMMARY.total*100);document.getElementById('unmapped').innerHTML=`<div><b>Data Health · cobertura geográfica</b><p>${SUMMARY.mapped} oportunidades con destino utilizable; ${missing} todavía no se dibujan. No se inventan ubicaciones.</p><div class="dataHealth"><div class="healthGauge"><i style="width:${p}%"></i></div><span class="healthPct">${p}%</span></div></div><div class="big">${missing}<span style="font-size:10px;color:#98a2b3"> gap</span></div>`};
function renderGapRadar(){const candidates=D.locations.filter(r=>r.scope!=='country'&&r.total>0).map(r=>{const pcs=profileCounts(r.name),div=Object.values(pcs).filter(Boolean).length;let gaps=[];if(r.sent>=3&&r.interested===0)gaps.push(['Conversión',3,`${r.sent} outreach y 0 interés`]);if(div<2&&r.total>=3)gaps.push(['Mix de perfiles',2,`${div}/4 perfiles cubiertos`]);if(r.next<r.total)gaps.push(['Ejecución',2,`${r.total-r.next} sin próximo paso`]);if(r.queue>=2)gaps.push(['Aprobación',2,`${r.queue} en cola`]);return{r,gaps,severity:gaps.reduce((a,g)=>a+g[1],0)}}).filter(x=>x.severity>0).sort((a,b)=>b.severity-a.severity||b.r.total-a.r.total).slice(0,4);const el=document.getElementById('radarGrid');if(!candidates.length){el.innerHTML='<div class="gapCard good"><div class="gapTop"><b>Sin gaps críticos</b><span class="gapScore">OK</span></div><p>La combinación actual no muestra bloqueos estructurales relevantes.</p></div>';return}el.innerHTML=candidates.map(x=>`<div class="gapCard ${x.severity>=3?'severe':''}"><div class="gapTop"><b>${x.r.name}</b><span class="gapScore">${x.r.marketScore}/100</span></div><p>${x.gaps.map(g=>g[0]+': '+g[2]).join(' · ')}</p><div class="gapAction">${nextBestAction(x.r)}</div></div>`).join('')}
const baseRefresh=refresh;refresh=function(fit=false){renderFilters();redrawCountries();redrawMarkers();renderLegend();document.getElementById('mode').textContent=label()+(profile!=='ALL'?' · '+PTYPE[profile]:'');document.getElementById('count').textContent=statCount()+' visibles';renderRoad();renderUnmapped();renderGapRadar();renderExecutiveIntel();if(selected?.type==='city')renderHeroCity(selected.name);else if(selected?.type==='country')renderCountry(selected.name);else defaultVisual();if(fit){if(view==='ROADMAP'){const rr=D.roadmap.filter(r=>quarter==='ALL'||r.quarter===quarter);if(rr.length)map.fitBounds(L.latLngBounds(rr.map(r=>[r.lat,r.lng])),{padding:[35,35]})}else fitVisible()}};
doSearch=function(){const q=document.getElementById('search').value.trim().toLowerCase();if(!q)return;const r=D.locations.find(x=>x.name.toLowerCase().includes(q)||x.country.toLowerCase().includes(q));if(r){selectCity(r.name);return}const f=FEATURED.find(x=>[x.name,x.person,x.company,x.city].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));if(f){selectCity(f.city);return}const rd=D.roadmap.find(x=>x.name.toLowerCase().includes(q)||x.country.toLowerCase().includes(q));if(rd){selectCity(rd.name,rd);return}document.getElementById('search').value='';document.getElementById('search').placeholder='Sin coincidencia · prueba otra ciudad, empresa o contacto'};
function boot(){try{if(typeof D==='undefined'||!D||typeof SUMMARY==='undefined'||!SUMMARY||typeof MATRIX==='undefined'||!MATRIX||typeof FEATURED==='undefined'||!FEATURED||typeof geo==='undefined'||!geo){setTimeout(boot,90);return}patchData();mountUI();view='PRIORITY';profile='ALL';funnel='ALL';quarter='ALL';v11Priority='P0';v11Activity='ALL';renderStats();refresh(true);document.getElementById('sync').textContent='● '+SNAPSHOT}catch(e){console.error('v11 init',e);setTimeout(boot,250)}}
boot();
})();